import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import { fetchTrivia } from "./loader-api";
import type { Question, Quiz } from "../../models/types";
import * as R from "ramda";
import { quizFactory } from "../../models/factories";

export interface LoaderState {
    quizzes: Quiz[];
    quizTags: string[];
    questionTags: string[];
    status: "idle" | "loading" | "failed";
    selectedQuestionTags: string[];
    selectedQuizTags: string[];
    selectedQuiz: string | null;
}


const initialState: LoaderState = {
    quizzes: [],
    quizTags: [],
    questionTags: [],
    status: "idle",
    selectedQuestionTags: [],
    selectedQuizTags: [],
    selectedQuiz: null
};

// Remove unpublished quizzes and sort by publish date
const quizFilterSort  = R.compose<any[], Quiz[], Quiz[], Quiz[], Quiz[]>(
     R.sort((a, b) => (b.publishDate - a.publishDate)),
     R.filter((q: Quiz) => q.publishDate <= Date.now()),
     R.filter((q: Quiz) => (new Date(q.publishDate)).toString() !== "Invalid Date"),
     R.filter((q: Quiz) => Boolean(q.publishDate))
);


export const fetchQuizzes = createAsyncThunk(
    "loader/loadQuizzes",
    async () => {
        const response = await fetchTrivia();
        return R.map(quizFactory)(response.quizzes);
    }
);

export const loaderSlice = createSlice({
    name: "loader",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        loadQuizzes: (state, action: PayloadAction<Quiz[]>) => {
            const extractQuizTags = R.compose(Array.from, (t: string[]) => new Set(t), R.flatten, R.map((q: Quiz) => q.tags));
            const extractQuestionTags = R.compose(
                Array.from,
                (t: string[]) => new Set(t),
                R.flatten,
                R.map((q: Question) => q.tags),
                R.flatten,
                R.map((q: Quiz) => q.questions)
            );
            state.quizzes = action.payload;
            state.quizTags = extractQuizTags(action.payload) as string[];
            state.questionTags = extractQuestionTags(action.payload) as string[];
        },
        setQuiz: (state, action: PayloadAction<string>) => {
            state.selectedQuiz = action.payload;
        },
        unsetQuiz: (state) => {
            state.selectedQuiz = null;
        },
        addQuizTag: (state, action: PayloadAction<string>) => {
            state.selectedQuizTags = R.compose(Array.from, (a) => (new Set(a)), state.selectedQuizTags.concat)(action.payload) as string[];
        },
        removeQuizTag: (state, action: PayloadAction<string>) => {
            state.selectedQuizTags = R.compose(Array.from, (a: string[]) => (new Set(a)), R.filter((x: string) => x !== action.payload))(state.selectedQuizTags) as string[];
        },
        clearQuizTags: (state) => {
            state.selectedQuizTags = [];
        },
        addQuestionTag: (state, action: PayloadAction<string>) => {
            state.selectedQuizTags = R.compose(Array.from, (a) => (new Set(a)), state.selectedQuestionTags.concat)(action.payload) as string[];
        },
        removeQuestionTag: (state, action: PayloadAction<string>) => {
            state.selectedQuestionTags = R.compose(Array.from, (a: string[]) => (new Set(a)), R.filter((x: string) => x !== action.payload))(state.selectedQuizTags) as string[];
        },
        clearQuestionTags: (state) => {
            state.selectedQuestionTags = [];
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchQuizzes.pending, (state) => {
                state.status = "loading";
            })
            .addCase(fetchQuizzes.fulfilled, (state, action) => {
                state.status = "idle";
                state.quizzes = action.payload;
            })
            .addCase(fetchQuizzes.rejected, (state) => {
                state.status = "failed";
            });
    }
});

export const {
    addQuestionTag,
    clearQuestionTags,
    removeQuestionTag,
    clearQuizTags,
    removeQuizTag,
    addQuizTag,
    setQuiz,
    unsetQuiz
} = loaderSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.loader.value)`
export const selectQuizzes = (state: RootState) => quizFilterSort(state.loader.quizzes);
export const selectLatestQuiz = (state: RootState) => quizFilterSort(state.loader.quizzes)[0];
export const selectQuizTags = (state: RootState) => state.loader.quizTags;
export const selectQuestionTags = (state: RootState) => state.loader.questionTags;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//     (amount: number): AppThunk =>
//         (dispatch, getState) => {
//             const currentValue = selectCount(getState());
//             if (currentValue % 2 === 1) {
//                 dispatch(incrementByAmount(amount));
//             }
//         };

export default loaderSlice.reducer;
